server:
  port: 9012
spring:
  application:
    name: springCloudConfig
  cloud:
    compatibility-verifier:
      enabled: false
    config:
      server:
        bootstrap: true
        git:
          uri: https://github.com/shakjaf110/springCloudConfigProperties.git
          username: shakjaf110
          password: St@r2326
          clone-on-start: true
          default-label: main
          searchPaths: '{application}'

logging:
  level:
    root: DEBUG